name: GoInventoryAPI CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-each-step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build and Test each step
        run: |
          for dir in step_*/; do
            echo "🔍 Verificando $dir"
            cd $dir
            if [ -f "go.mod" ]; then
              echo "📦 Rodando build em $dir"
              go mod tidy
              go build -v ./...
              go test -v ./... || echo "⚠️ Sem testes em $dir"
            else
              echo "⚠️ Sem go.mod em $dir — pulando"
            fi
            cd ..
          done
